import type { ChatMessage, ToolResult } from './types.d.ts';

export function resetToolAndEventState(): void;
export function resetChatUI(): void;
export function setStatus(statusState: string, text: string): void;
export function addMsg(type: string, text: string, eventId?: string): void;
export function addErrorMsg(text: string, onRetry?: (() => void) | null): void;
export function addToolCall(name: string, params: Record<string, unknown>, result: ToolResult): void;
export function renderToolCalls(): void;
export function addInlineToolCall(name: string, params: Record<string, unknown>, result: ToolResult): HTMLElement;
export function updateInlineToolCall(el: HTMLElement, name: string, params: Record<string, unknown>, result: ToolResult): void;
export function addEvent(topic: string, payload: unknown): void;
export function updateState(): void;
export function updateCostDisplay(): void;
export function createStreamingMsg(): HTMLElement;
export function appendToStreamingMsg(el: HTMLElement, text: string): void;
export function finalizeStreamingMsg(el: HTMLElement): void;
export function persistActiveConversation(): Promise<void>;
export function updateConvNameDisplay(): void;
export function renameCurrentConversation(name: string): Promise<void>;
export function newConversation(): Promise<void>;
export function switchConversation(convId: string): Promise<void>;
export function deleteConversationEntry(convId: string): Promise<void>;
export function forkConversation(): Promise<void>;
export function forkConversationFromEvent(eventId: string): Promise<void>;
export function exportConversationAsJSON(): string;
export function exportConversationAsText(): string;
export let convItemBar: { refresh: () => void; destroy: () => void } | null;
export function replaySessionHistory(history: ChatMessage[]): void;
export function replayFromEvents(events: Array<{ type: string; data: unknown; timestamp?: number }>): void;
export function addSubAgentCard(task: string, opts?: { status?: string; iterations?: number; toolCalls?: number }): HTMLElement;
export function updateSubAgentCard(el: HTMLElement, task: string, opts?: { status?: string; summary?: string; iterations?: number; toolCalls?: number }): void;
export function addSafetyBanner(details: { level?: string; message?: string; [key: string]: unknown }): void;
export function addUndoButton(onUndo: () => void): HTMLElement;
export function addIntentBadge(intent: string): void;
export function buildDynamicSystemPrompt(basePrompt: string, memories: string, goals: string, skillMetadata: string, activeSkillPrompts: string[]): string;
export function sendMessage(): Promise<void>;
export function initChatListeners(): void;
