export function applySecuritySettings(): void;
export function renderAutonomySection(): void;
export function saveAutonomySettings(): void;
export function updateCostMeter(): void;
export function updateAutonomyBadge(): void;
export function renderIdentitySection(): void;
export function saveIdentitySettings(): void;
export function renderRoutingSection(): Promise<void>;
export function renderAuthProfilesSection(): void;
export function saveSelfRepairSettings(): void;
export function renderSelfRepairSection(): void;
export function updateCacheStats(): void;
export function saveLimitsSettings(): void;
export function renderLimitsSection(): void;
export function saveSandboxSettings(): void;
export function renderSandboxSection(): void;
export function saveHeartbeatSettings(): void;
export function renderHeartbeatSection(): void;
export function renderOAuthSection(): void;
export function renderCleanConversationsSection(): void;
export function updateDaemonBadge(phase: string): void;
export function updateRemoteBadge(count: number): void;
export function refreshDashboard(): void;
export function renderApiKeyWarning(): void;
export function renderQuotaBar(): Promise<void>;
